import = ["~/.config/alacritty/_active.toml"]
live_config_reload= true
[env]
TERM = "xterm-256color"
ALACRITTY = "true"

[window]
decorations = "buttonless"
dynamic_padding = false

[window.padding]
x = 5
y = 10 

[font]
size = 15.0

[font.normal]
family = "SauceCodePro Nerd Font"
style = "Medium"

[font.bold]
family = "SauceCodePro Nerd Font"
  style = "Heavy"

[font.bold_italic]
family = "SauceCodePro Nerd Font"
style = "Heavy Italic"

[font.italic]
family = "SauceCodePro Nerd Font"
style = "Medium Italic"


